### ISSUE TITLE
twice install

### ISSUE THREAD

**Issue by region51** [surfernsk/mpv#2]
Привет, вот хочу поинтересоваться, зачем в спеке ?

```
desktop-file-install etc/mpv.desktop

for RES in 16 32 64; do
  install -Dpm 644 etc/mpv-icon-8bit-${RES}x${RES}.png %{buildroot}%{_datadir}/icons/hicolor/${RES}x${RES}/apps/%{name}.png
done
install -Dpm 644 etc/%{name}-gradient.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/%{name}-gradient.svg
install -Dpm 644 etc/%{name}-symbolic.svg %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps/%{name}-symbolic.svg
install -Dpm 644 etc/%{name}.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg
```

если установка идет автоматом
```
+ install /builddir/build/BUILDROOT/mpv-0.15.0-1.fc22.x86_64/usr/share/applications/mpv.desktop (from etc/mpv.desktop)
+ install /builddir/build/BUILDROOT/mpv-0.15.0-1.fc22.x86_64/usr/share/icons/hicolor/16x16/apps/mpv.png (from etc/mpv-icon-8bit-16x16.png)
+ install /builddir/build/BUILDROOT/mpv-0.15.0-1.fc22.x86_64/usr/share/icons/hicolor/32x32/apps/mpv.png (from etc/mpv-icon-8bit-32x32.png)
+ install /builddir/build/BUILDROOT/mpv-0.15.0-1.fc22.x86_64/usr/share/icons/hicolor/64x64/apps/mpv.png (from etc/mpv-icon-8bit-64x64.png)
+ install /builddir/build/BUILDROOT/mpv-0.15.0-1.fc22.x86_64/usr/share/icons/hicolor/scalable/apps/mpv.svg (from etc/mpv-gradient.svg)
```
единственное, что надо прописать, это mpv-symbolic.svg
то есть у тебя и rpmfusion, где ты делаешь PR установка проходит дважды ... это хорошо видно в твоем логе http://pastebin.com/raw/VWZ9cVBH

такая же беда с конфигами
```
предупреждение: Файл указан дважды: /usr/share/doc/mpv/input.conf
предупреждение: Файл указан дважды: /usr/share/doc/mpv/mplayer-input.conf
предупреждение: Файл указан дважды: /usr/share/doc/mpv/mpv.conf
предупреждение: Файл указан дважды: /usr/share/doc/mpv/restore-old-bindings.conf
```

и вообще input.conf и mpv.conf это просто примеры https://github.com/mpv-player/mpv/pull/2704
где сам автор пишет
>The other conf files are fully documented and are just examples.

так зачем их в /etc определять то?

PS. И еще ты дважды прописал в pull requests
BuildRequires:  pkgconfig(gl)

**Comment by region51** [comment]
PS. ALSO

нет у mpv схемы, так зачем 
glib-compile-schemas %{_datadir}/glib-2.0/schemas &> /dev/null || :

**Comment by surfernsk** [comment]
Привет, спек был позаимствован из rpmfusion.
Спасибо за замечания.
Вычищать спек буду, по мере свободного времени.

**Comment by surfernsk** [comment]
Немного вычистил, вот только различие в обработке %doc в F22 и F23 несколько напрягло.

**Comment by region51** [comment]
@surfernsk Привет, это не проблема. 
Сделай как у меня https://github.com/RussianFedora/mpv/blob/master/mpv.spec
